baseURL = 'https://frieren360.github.io'
languageCode = 'en-gb'
title = "Frieren360's Site"
theme = 'hugo-theme-stack'

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[params]
  [params.sidebar]
    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.jpg"
  [params.widgets]
    [[params.widgets.homepage]]
    type = "search"
    [[params.widgets.homepage]]
    type = "archives"
    [params.widgets.homepage.params]
    limit = 5
    [[params.widgets.homepage]]
    type = "categories"
